# version: "3.8"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - app_blue
      - app_green
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - PORT=${PORT}
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx/start-nginx.sh:/start-nginx.sh:ro
    command: ["/bin/sh", "/start-nginx.sh"]

  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - APP_POOL=blue
      - PORT=${PORT}
    ports:
      - "8081:${PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/healthz"]
      interval: 3s
      timeout: 2s
      retries: 2

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - APP_POOL=green
      - PORT=${PORT}
    ports:
      - "8082:${PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/healthz"]
      interval: 3s
      timeout: 2s
      retries: 2
